### ISSUE TITLE
Задание 2

### ISSUE THREAD

**Issue by d-qql** [egorsvitov/mipt-sle#1]
1) Тут: https://github.com/egorsvitov/mipt-sle/blob/510652276b5688d43cbc80c537be8f8f1897ed22/dense_vs_csr/src/matrices.hpp#L90C1-L98C14

получил умножение в лучшем случае за O(n^2), а в худшем O(n^3). Должно быть в лучшем случае за O(n), а в худшем O(n^2), нужно переделать. Поэтому и графики неправильные вышли, показывал на семинаре

2) Пройтись по https://github.com/MIPT-SLE/UnforgivableCurses и убрать все запрещенное из кода

**Comment by egorsvitov** [comment]
https://github.com/egorsvitov/mipt-sle/commit/d5acd6c887b722d48152cbc53773173f9b014c2b
